let mapData = [];
let provinceList = ["WESTERN", "EASTERN", "SOUTHERN", "NOTHERN", "NORTH WESTERN", "NORTH CENTRAL", "CENTRAL", "SABARAGAMUWA","UVA"];
let districtList = [{
    "PROVINCE":provinceList[0],
    "DISTRICT":"GAMPAHA"
},{
    "PROVINCE":provinceList[0],
    "DISTRICT":"COLOMBO"
},{
    "PROVINCE":provinceList[0],
    "DISTRICT":"KALUTARA"
},{
    "PROVINCE":provinceList[1],
    "DISTRICT":"TRINCOMALEE"
},{
    "PROVINCE":provinceList[1],
    "DISTRICT":"AMPARA"
},{
    "PROVINCE":provinceList[1],
    "DISTRICT":"GAMPAHA"
},{
    "PROVINCE":provinceList[2],
    "DISTRICT":"HAMBANTOTA"
},{
    "PROVINCE":provinceList[2],
    "DISTRICT":"MATARA"
},{
    "PROVINCE":provinceList[2],
    "DISTRICT":"GALLE"
},{
    "PROVINCE":provinceList[3],
    "DISTRICT":"JAFFNA"
},{
    "PROVINCE":provinceList[3],
    "DISTRICT":"KILINOCHCHI"
},{
    "PROVINCE":provinceList[3],
    "DISTRICT":"MANNAR"
},{
    "PROVINCE":provinceList[3],
    "DISTRICT":"MULLAITIVU"
},{
    "PROVINCE":provinceList[3],
    "DISTRICT":"VAVUNIYA"
},{
    "PROVINCE":provinceList[4],
    "DISTRICT":"PUTTALAM"
},{
    "PROVINCE":provinceList[4],
    "DISTRICT":"KURUNEGALA"
},{
    "PROVINCE":provinceList[5],
    "DISTRICT":"ANURADHAPURA"
},{
    "PROVINCE":provinceList[5],
    "DISTRICT":"POLONNARUWA"
},{
    "PROVINCE":provinceList[6],
    "DISTRICT":"MATALE"
},{
    "PROVINCE":provinceList[6],
    "DISTRICT":"KANDY"
},{
    "PROVINCE":provinceList[6],
    "DISTRICT":"NUWARA ELIYA"
},{
    "PROVINCE":provinceList[7],
    "DISTRICT":"KEGALLE"
},{
    "PROVINCE":provinceList[7],
    "DISTRICT":"RATNAPURA"
},{
    "PROVINCE":provinceList[8],
    "DISTRICT":"BADULLA"
},{
    "PROVINCE":provinceList[8],
    "DISTRICT":"MONARAGALA"
}];
let divisional_secretariats = [{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"ATTANAGALLA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"BIYAGAMA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"DIVULAPITIYA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"DOMPE"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"GAMPAHA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"JA-ELA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"KATANA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"KELANIYA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"MAHARA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"MINUWANGODA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"MIRIGAMA"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"NEGAMBO"
},{
    "DISTRICT":districtList[0],
    "DIVISIONAL_SECRETARIAST":"WATTALA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"COLOMBO"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"DEHIWALA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"HOMAGAMA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"KADUWELA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"KESBEWA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"KOLONNAWA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"MAHARAGAMA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"MORATUWA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"PADUKKA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"RATMALANA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"SEETHAWAKA"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"SRI JAYAWARDHANAPURA KOTTE"
},{
    "DISTRICT":districtList[1],
    "DIVISIONAL_SECRETARIAST":"THIMBIRIGASYAYA"
},{
    "DISTRICT":districtList[2],
    "DIVISIONAL_SECRETARIAST":"THIMBIRIGASYAYA"
},]